# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'shuju' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
 pod 'MJRefresh', '~> 3.1.0'
    pod 'FMDB', '~> 2.6.2'
     pod 'SDAutoLayout', '~> 1.52'
      pod 'SDWebImage', '~> 3.7.5'
  # Pods for shuju

  target 'shujuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shujuUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
